#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : catch2
Version  : 3.6.0
Release  : 8
URL      : https://github.com/catchorg/Catch2/archive/v3.6.0/Catch2-3.6.0.tar.gz
Source0  : https://github.com/catchorg/Catch2/archive/v3.6.0/Catch2-3.6.0.tar.gz
Summary  : A modern, C++-native, test framework for C++14 and above
Group    : Development/Tools
License  : BSL-1.0
Requires: catch2-data = %{version}-%{release}
Requires: catch2-lib = %{version}-%{release}
Requires: catch2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : python3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<a id="top"></a>
![Catch2 logo](data/artwork/catch2-logo-small-with-background.png)

%package data
Summary: data components for the catch2 package.
Group: Data

%description data
data components for the catch2 package.


%package dev
Summary: dev components for the catch2 package.
Group: Development
Requires: catch2-lib = %{version}-%{release}
Requires: catch2-data = %{version}-%{release}
Provides: catch2-devel = %{version}-%{release}
Requires: catch2 = %{version}-%{release}

%description dev
dev components for the catch2 package.


%package doc
Summary: doc components for the catch2 package.
Group: Documentation

%description doc
doc components for the catch2 package.


%package lib
Summary: lib components for the catch2 package.
Group: Libraries
Requires: catch2-data = %{version}-%{release}
Requires: catch2-license = %{version}-%{release}

%description lib
lib components for the catch2 package.


%package license
Summary: license components for the catch2 package.
Group: Default

%description license
license components for the catch2 package.


%prep
%setup -q -n Catch2-3.6.0
cd %{_builddir}/Catch2-3.6.0
pushd ..
cp -a Catch2-3.6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719953645
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719953645
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/catch2
cp %{_builddir}/Catch2-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/catch2/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/Catch2/gdbinit
/usr/share/Catch2/lldbinit

%files dev
%defattr(-,root,root,-)
/usr/include/catch2/benchmark/catch_benchmark.hpp
/usr/include/catch2/benchmark/catch_benchmark_all.hpp
/usr/include/catch2/benchmark/catch_chronometer.hpp
/usr/include/catch2/benchmark/catch_clock.hpp
/usr/include/catch2/benchmark/catch_constructor.hpp
/usr/include/catch2/benchmark/catch_environment.hpp
/usr/include/catch2/benchmark/catch_estimate.hpp
/usr/include/catch2/benchmark/catch_execution_plan.hpp
/usr/include/catch2/benchmark/catch_optimizer.hpp
/usr/include/catch2/benchmark/catch_outlier_classification.hpp
/usr/include/catch2/benchmark/catch_sample_analysis.hpp
/usr/include/catch2/benchmark/detail/catch_analyse.hpp
/usr/include/catch2/benchmark/detail/catch_benchmark_function.hpp
/usr/include/catch2/benchmark/detail/catch_benchmark_stats.hpp
/usr/include/catch2/benchmark/detail/catch_benchmark_stats_fwd.hpp
/usr/include/catch2/benchmark/detail/catch_complete_invoke.hpp
/usr/include/catch2/benchmark/detail/catch_estimate_clock.hpp
/usr/include/catch2/benchmark/detail/catch_measure.hpp
/usr/include/catch2/benchmark/detail/catch_repeat.hpp
/usr/include/catch2/benchmark/detail/catch_run_for_at_least.hpp
/usr/include/catch2/benchmark/detail/catch_stats.hpp
/usr/include/catch2/benchmark/detail/catch_timing.hpp
/usr/include/catch2/catch_all.hpp
/usr/include/catch2/catch_approx.hpp
/usr/include/catch2/catch_assertion_info.hpp
/usr/include/catch2/catch_assertion_result.hpp
/usr/include/catch2/catch_config.hpp
/usr/include/catch2/catch_get_random_seed.hpp
/usr/include/catch2/catch_message.hpp
/usr/include/catch2/catch_section_info.hpp
/usr/include/catch2/catch_session.hpp
/usr/include/catch2/catch_tag_alias.hpp
/usr/include/catch2/catch_tag_alias_autoregistrar.hpp
/usr/include/catch2/catch_template_test_macros.hpp
/usr/include/catch2/catch_test_case_info.hpp
/usr/include/catch2/catch_test_macros.hpp
/usr/include/catch2/catch_test_spec.hpp
/usr/include/catch2/catch_timer.hpp
/usr/include/catch2/catch_tostring.hpp
/usr/include/catch2/catch_totals.hpp
/usr/include/catch2/catch_translate_exception.hpp
/usr/include/catch2/catch_user_config.hpp
/usr/include/catch2/catch_version.hpp
/usr/include/catch2/catch_version_macros.hpp
/usr/include/catch2/generators/catch_generator_exception.hpp
/usr/include/catch2/generators/catch_generators.hpp
/usr/include/catch2/generators/catch_generators_adapters.hpp
/usr/include/catch2/generators/catch_generators_all.hpp
/usr/include/catch2/generators/catch_generators_random.hpp
/usr/include/catch2/generators/catch_generators_range.hpp
/usr/include/catch2/interfaces/catch_interfaces_all.hpp
/usr/include/catch2/interfaces/catch_interfaces_capture.hpp
/usr/include/catch2/interfaces/catch_interfaces_config.hpp
/usr/include/catch2/interfaces/catch_interfaces_enum_values_registry.hpp
/usr/include/catch2/interfaces/catch_interfaces_exception.hpp
/usr/include/catch2/interfaces/catch_interfaces_generatortracker.hpp
/usr/include/catch2/interfaces/catch_interfaces_registry_hub.hpp
/usr/include/catch2/interfaces/catch_interfaces_reporter.hpp
/usr/include/catch2/interfaces/catch_interfaces_reporter_factory.hpp
/usr/include/catch2/interfaces/catch_interfaces_tag_alias_registry.hpp
/usr/include/catch2/interfaces/catch_interfaces_test_invoker.hpp
/usr/include/catch2/interfaces/catch_interfaces_testcase.hpp
/usr/include/catch2/internal/catch_assertion_handler.hpp
/usr/include/catch2/internal/catch_case_insensitive_comparisons.hpp
/usr/include/catch2/internal/catch_case_sensitive.hpp
/usr/include/catch2/internal/catch_clara.hpp
/usr/include/catch2/internal/catch_commandline.hpp
/usr/include/catch2/internal/catch_compare_traits.hpp
/usr/include/catch2/internal/catch_compiler_capabilities.hpp
/usr/include/catch2/internal/catch_config_android_logwrite.hpp
/usr/include/catch2/internal/catch_config_counter.hpp
/usr/include/catch2/internal/catch_config_prefix_messages.hpp
/usr/include/catch2/internal/catch_config_static_analysis_support.hpp
/usr/include/catch2/internal/catch_config_uncaught_exceptions.hpp
/usr/include/catch2/internal/catch_config_wchar.hpp
/usr/include/catch2/internal/catch_console_colour.hpp
/usr/include/catch2/internal/catch_console_width.hpp
/usr/include/catch2/internal/catch_container_nonmembers.hpp
/usr/include/catch2/internal/catch_context.hpp
/usr/include/catch2/internal/catch_debug_console.hpp
/usr/include/catch2/internal/catch_debugger.hpp
/usr/include/catch2/internal/catch_decomposer.hpp
/usr/include/catch2/internal/catch_enforce.hpp
/usr/include/catch2/internal/catch_enum_values_registry.hpp
/usr/include/catch2/internal/catch_errno_guard.hpp
/usr/include/catch2/internal/catch_exception_translator_registry.hpp
/usr/include/catch2/internal/catch_fatal_condition_handler.hpp
/usr/include/catch2/internal/catch_floating_point_helpers.hpp
/usr/include/catch2/internal/catch_getenv.hpp
/usr/include/catch2/internal/catch_is_permutation.hpp
/usr/include/catch2/internal/catch_istream.hpp
/usr/include/catch2/internal/catch_jsonwriter.hpp
/usr/include/catch2/internal/catch_lazy_expr.hpp
/usr/include/catch2/internal/catch_leak_detector.hpp
/usr/include/catch2/internal/catch_list.hpp
/usr/include/catch2/internal/catch_logical_traits.hpp
/usr/include/catch2/internal/catch_message_info.hpp
/usr/include/catch2/internal/catch_meta.hpp
/usr/include/catch2/internal/catch_move_and_forward.hpp
/usr/include/catch2/internal/catch_noncopyable.hpp
/usr/include/catch2/internal/catch_optional.hpp
/usr/include/catch2/internal/catch_output_redirect.hpp
/usr/include/catch2/internal/catch_parse_numbers.hpp
/usr/include/catch2/internal/catch_platform.hpp
/usr/include/catch2/internal/catch_polyfills.hpp
/usr/include/catch2/internal/catch_preprocessor.hpp
/usr/include/catch2/internal/catch_preprocessor_internal_stringify.hpp
/usr/include/catch2/internal/catch_preprocessor_remove_parens.hpp
/usr/include/catch2/internal/catch_random_floating_point_helpers.hpp
/usr/include/catch2/internal/catch_random_integer_helpers.hpp
/usr/include/catch2/internal/catch_random_number_generator.hpp
/usr/include/catch2/internal/catch_random_seed_generation.hpp
/usr/include/catch2/internal/catch_reporter_registry.hpp
/usr/include/catch2/internal/catch_reporter_spec_parser.hpp
/usr/include/catch2/internal/catch_result_type.hpp
/usr/include/catch2/internal/catch_reusable_string_stream.hpp
/usr/include/catch2/internal/catch_run_context.hpp
/usr/include/catch2/internal/catch_section.hpp
/usr/include/catch2/internal/catch_sharding.hpp
/usr/include/catch2/internal/catch_singletons.hpp
/usr/include/catch2/internal/catch_source_line_info.hpp
/usr/include/catch2/internal/catch_startup_exception_registry.hpp
/usr/include/catch2/internal/catch_stdstreams.hpp
/usr/include/catch2/internal/catch_stream_end_stop.hpp
/usr/include/catch2/internal/catch_string_manip.hpp
/usr/include/catch2/internal/catch_stringref.hpp
/usr/include/catch2/internal/catch_tag_alias_registry.hpp
/usr/include/catch2/internal/catch_template_test_registry.hpp
/usr/include/catch2/internal/catch_test_case_info_hasher.hpp
/usr/include/catch2/internal/catch_test_case_registry_impl.hpp
/usr/include/catch2/internal/catch_test_case_tracker.hpp
/usr/include/catch2/internal/catch_test_failure_exception.hpp
/usr/include/catch2/internal/catch_test_macro_impl.hpp
/usr/include/catch2/internal/catch_test_registry.hpp
/usr/include/catch2/internal/catch_test_run_info.hpp
/usr/include/catch2/internal/catch_test_spec_parser.hpp
/usr/include/catch2/internal/catch_textflow.hpp
/usr/include/catch2/internal/catch_to_string.hpp
/usr/include/catch2/internal/catch_uncaught_exceptions.hpp
/usr/include/catch2/internal/catch_uniform_floating_point_distribution.hpp
/usr/include/catch2/internal/catch_uniform_integer_distribution.hpp
/usr/include/catch2/internal/catch_unique_name.hpp
/usr/include/catch2/internal/catch_unique_ptr.hpp
/usr/include/catch2/internal/catch_void_type.hpp
/usr/include/catch2/internal/catch_wildcard_pattern.hpp
/usr/include/catch2/internal/catch_windows_h_proxy.hpp
/usr/include/catch2/internal/catch_xmlwriter.hpp
/usr/include/catch2/matchers/catch_matchers.hpp
/usr/include/catch2/matchers/catch_matchers_all.hpp
/usr/include/catch2/matchers/catch_matchers_container_properties.hpp
/usr/include/catch2/matchers/catch_matchers_contains.hpp
/usr/include/catch2/matchers/catch_matchers_exception.hpp
/usr/include/catch2/matchers/catch_matchers_floating_point.hpp
/usr/include/catch2/matchers/catch_matchers_predicate.hpp
/usr/include/catch2/matchers/catch_matchers_quantifiers.hpp
/usr/include/catch2/matchers/catch_matchers_range_equals.hpp
/usr/include/catch2/matchers/catch_matchers_string.hpp
/usr/include/catch2/matchers/catch_matchers_templated.hpp
/usr/include/catch2/matchers/catch_matchers_vector.hpp
/usr/include/catch2/matchers/internal/catch_matchers_impl.hpp
/usr/include/catch2/reporters/catch_reporter_automake.hpp
/usr/include/catch2/reporters/catch_reporter_common_base.hpp
/usr/include/catch2/reporters/catch_reporter_compact.hpp
/usr/include/catch2/reporters/catch_reporter_console.hpp
/usr/include/catch2/reporters/catch_reporter_cumulative_base.hpp
/usr/include/catch2/reporters/catch_reporter_event_listener.hpp
/usr/include/catch2/reporters/catch_reporter_helpers.hpp
/usr/include/catch2/reporters/catch_reporter_json.hpp
/usr/include/catch2/reporters/catch_reporter_junit.hpp
/usr/include/catch2/reporters/catch_reporter_multi.hpp
/usr/include/catch2/reporters/catch_reporter_registrars.hpp
/usr/include/catch2/reporters/catch_reporter_sonarqube.hpp
/usr/include/catch2/reporters/catch_reporter_streaming_base.hpp
/usr/include/catch2/reporters/catch_reporter_tap.hpp
/usr/include/catch2/reporters/catch_reporter_teamcity.hpp
/usr/include/catch2/reporters/catch_reporter_xml.hpp
/usr/include/catch2/reporters/catch_reporters_all.hpp
/usr/lib64/cmake/Catch2/Catch.cmake
/usr/lib64/cmake/Catch2/Catch2Config.cmake
/usr/lib64/cmake/Catch2/Catch2ConfigVersion.cmake
/usr/lib64/cmake/Catch2/Catch2Targets-relwithdebinfo.cmake
/usr/lib64/cmake/Catch2/Catch2Targets.cmake
/usr/lib64/cmake/Catch2/CatchAddTests.cmake
/usr/lib64/cmake/Catch2/CatchShardTests.cmake
/usr/lib64/cmake/Catch2/CatchShardTestsImpl.cmake
/usr/lib64/cmake/Catch2/ParseAndAddCatchTests.cmake
/usr/lib64/libCatch2.so
/usr/lib64/libCatch2Main.so
/usr/lib64/pkgconfig/catch2-with-main.pc
/usr/lib64/pkgconfig/catch2.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/Catch2/Readme.md
/usr/share/doc/Catch2/assertions.md
/usr/share/doc/Catch2/benchmarks.md
/usr/share/doc/Catch2/ci-and-misc.md
/usr/share/doc/Catch2/cmake-integration.md
/usr/share/doc/Catch2/command-line.md
/usr/share/doc/Catch2/commercial-users.md
/usr/share/doc/Catch2/comparing-floating-point-numbers.md
/usr/share/doc/Catch2/configuration.md
/usr/share/doc/Catch2/contributing.md
/usr/share/doc/Catch2/deprecations.md
/usr/share/doc/Catch2/event-listeners.md
/usr/share/doc/Catch2/faq.md
/usr/share/doc/Catch2/generators.md
/usr/share/doc/Catch2/limitations.md
/usr/share/doc/Catch2/list-of-examples.md
/usr/share/doc/Catch2/logging.md
/usr/share/doc/Catch2/matchers.md
/usr/share/doc/Catch2/migrate-v2-to-v3.md
/usr/share/doc/Catch2/opensource-users.md
/usr/share/doc/Catch2/other-macros.md
/usr/share/doc/Catch2/own-main.md
/usr/share/doc/Catch2/release-notes.md
/usr/share/doc/Catch2/release-process.md
/usr/share/doc/Catch2/reporter-events.md
/usr/share/doc/Catch2/reporters.md
/usr/share/doc/Catch2/skipping-passing-failing.md
/usr/share/doc/Catch2/test-cases-and-sections.md
/usr/share/doc/Catch2/test-fixtures.md
/usr/share/doc/Catch2/tostring.md
/usr/share/doc/Catch2/tutorial.md
/usr/share/doc/Catch2/usage-tips.md
/usr/share/doc/Catch2/why-catch.md

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libCatch2.so.3.6.0
/V3/usr/lib64/libCatch2Main.so.3.6.0
/usr/lib64/libCatch2.so.3.6.0
/usr/lib64/libCatch2Main.so.3.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/catch2/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
